#>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
#   ExpManager ConfigFile!
#   Author SiriuseR(dejiplus)
#   License GPLv3
#<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

spawn:
   world: 'lobby'
   x: '0.5'
   y: '80'
   z: '0.5'

#>>>>>>>>>>>>>>>>>>>>>>#
#   Format Config      #
#<<<<<<<<<<<<<<<<<<<<<<#
format:
   join: '%PREFIX%&e%PLAYER% joined the game.'
   quit: '%PREFIX%&e%PLAYER% left the game.'
   chat: '%PREFIX%&7%PLAYER%&f: %MESSAGE%'

#>>>>>>>>>>>>>>>>>>>>>>#
#   Debug Config       #
#<<<<<<<<<<<<<<<<<<<<<<#
Debug: false

#>>>>>>>>>>>>>>>>>>>>>>#
#   DO NOT TOUCH       #
#<<<<<<<<<<<<<<<<<<<<<<#
ConfigVersion: 1